services:
  - type: web
    name: barlo-portfolio-api
    env: docker
    dockerfilePath: ./Server/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: Smtp__Host
        sync: false
      - key: Smtp__Port
        value: "587"
      - key: Smtp__Username
        sync: false
      - key: Smtp__Password
        sync: false
      - key: Smtp__EnableSsl
        value: "true"
      - key: Smtp__FromAddress
        sync: false
      - key: Smtp__ToAddress
        value: bawloordiales@gmail.com

  - type: web
    name: barlo-portfolio
    env: static
    buildCommand: dotnet publish BarloPortfolio.csproj -c Release -o publish_output
    staticPublishPath: ./publish_output/wwwroot
